name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}

    - name: Build Backend Image
      run: |
        docker build -t ${{ env.DOCKERHUB_USERNAME }}/fullstack-backend:latest ./full-stack-app/backend

    - name: Build Frontend Image
      run: |
        docker build -t ${{ env.DOCKERHUB_USERNAME }}/fullstack-frontend:latest ./full-stack-app/frontend

    - name: Push Backend Image
      run: |
        docker push ${{ env.DOCKERHUB_USERNAME }}/fullstack-backend:latest

    - name: Push Frontend Image
      run: |
        docker push ${{ env.DOCKERHUB_USERNAME }}/fullstack-frontend:latest
